wandb_version: 1

model_path:
  desc: null
  value: /data/puma_envs/FingerPrintMatchingModels/diffusion/model_embeddings_diffusion.pth
data_path:
  desc: null
  value: /data/puma_envs/img_l2_feature_extractions/enhance_control_generated
output_folder:
  desc: null
  value: /data/puma_envs/FingerPrintMatchingModels/diffusion/diffusion_pretrain_results
wandb_project:
  desc: null
  value: fingerprint_correlation
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709429912.684846
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.15.10
      8:
      - 5
