wandb_version: 1

model_path:
  desc: null
  value: /data/puma_envs/FingerPrintMatchingModels/model_embeddings_printsgan.pth
data_path:
  desc: null
  value: /data/therealgabeguo/printsgan
output_folder:
  desc: null
  value: /data/puma_envs/FingerPrintMatchingModels/printsgan_pretrain_results
wandb_project:
  desc: null
  value: fingerprint_correlation
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709224120.432789
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.15.10
      8:
      - 5
